# Generated by Django 2.2 on 2019-05-08 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='how we can help?', max_length=1000)),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='founds.Found')),
            ],
        ),
        migrations.CreateModel(
            name='HelpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a type of help which you need', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HelpInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for your zapros', primary_key=True, serialize=False)),
                ('ask', models.CharField(max_length=200)),
                ('answer', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('r', 'Readed'), ('f', 'Founding'), ('rr', 'Ready'), ('p', 'In process')], default='r', help_text='We started founding', max_length=1)),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='founds.Found')),
            ],
        ),
    ]
